### ISSUE TITLE
How to create a new postgis database?

### ISSUE THREAD

**Issue by dnltsk** [GeographicaGS/Docker-PostGIS#9]
I am expecting a prepared "template_postgis" DB which I can use to create my own PostGIS database
`createdb -U postgres -w -T template_postgis new_postgis_db`
But there are only three databases namely "postgres", "template0" and "template1" - all without PostGIS functionality.
So how can I create a new PostGIS database without downloading the template manually?

I am using geographica/postgis:postgresql-9.5.0-postgis-2.2.1-gdal-2.0.2-patched

Thanks and best regards,
Daniel

**Comment by malkab** [comment]
Hi Daniel, thanks for dropping by. The fact that the template is missing is because we like to have full control of the process and fine tune some aspects of the database creation process. But is rather easy:

``` Shell
createdb -U postgres -w new_postgis_db
```

Then, you can either log into the new database and issue:

``` SQL
create extension postgis;
```

as the superuser or, from the command line:

``` Shell
psql -h host -p port -U postgres new_postgis_db -c "create extension postgis;"
```

Hope this helps!
